name: GitHub Actions Backend Unit Tests
run-name: ${{ github.actor }} is running the backend tests
on:
  push:
    branches: 
    - "main"
jobs:
  Backend-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend
      - run: npm install
      - name: Use Firebase Admin SDK Key
      - run: echo "${{ secrets.FIREBASE_ADMIN_SDK_KEY }}" > ~/backend/runio-401718-firebase-adminsdk-ezjsi-797731a4a0.js
      - run: npm test
